In [2]:
#numpy 배열 기본
import numpy as np
v1=np.array([1,2,3,4,])
print(v1)

[1 2 3 4]


In [10]:
#np aragange or np arange 연속되거나 일정한 규칙을 가진 숫자
v1=np.arange(5)
print(v1)
#규칙성
v2=np.arange(1,10,2, dtype=int) #1투터 10까지 2간격으로 출력, 데이터 타입은 정수
v3=np.arange(3.5,10.5,2, dtype=float) #3.5부터 10.5까지 2간격으로 출력, 데이터타입은 실수
print(v2)
print(v3)
#제곱값
v4=np.arange(1,10,2)**2 #1부터 10까지 2간격의 숫자를 제곱
print(v4)

[0 1 2 3 4]
[1 3 5 7 9]
[3.5 5.5 7.5 9.5]
[ 1  9 25 49 81]


In [13]:
#행렬
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,6)
print(v2)
v3=v1.reshape(2,6, order='f')
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [19]:
#계산
v1=np.arange(1,5).reshape(2,2) #1~5까지의 배열을 만들고 행렬로 바로 전환
print(v1)
print(np.add(v1,v1))
print(np.subtract(v1,v1))

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
